#! /bin/sh
### BEGIN INIT INFO
# Provides:          vintageBrain
# Required-Start:
# Required-Stop:
# Default-Start:     2 3 4 5 6
# Default-Stop:      0 6
# Short-Description: Manages the general communication between elements of the Vintage Toy Synthesiser
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
    start)
	echo "Starting vintageBrain"
	/usr/VintageToySynthProject/VintageBrain/vintageBrain &
        ;;
    restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
    stop)
	echo "Stopping vintageBrain"
	ps -ef | grep vintageBrain | grep -v grep |awk '{ print $2 }' | xargs kill -9 
        ;;
    *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
